import {
  Droplets,
  Wrench,
  Flame,
  Bath,
  Thermometer,
  Search,
  Clock,
  Shield,
  Banknote,
  Award,
  ThumbsUp,
  Headphones,
  Phone,
  Mail,
  MapPin,
  ChevronDown,
  ChevronUp,
  Menu,
  X,
  Star,
  ArrowRight,
  Settings,
  ExternalLink,
  RotateCcw,
  Save,
  CheckCircle,
  AlertCircle,
  type LucideProps,
} from "lucide-react";

const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  droplets: Droplets,
  wrench: Wrench,
  flame: Flame,
  bath: Bath,
  thermometer: Thermometer,
  search: Search,
  clock: Clock,
  shield: Shield,
  banknote: Banknote,
  award: Award,
  thumbsUp: ThumbsUp,
  headphones: Headphones,
  phone: Phone,
  mail: Mail,
  mapPin: MapPin,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  menu: Menu,
  x: X,
  star: Star,
  arrowRight: ArrowRight,
  settings: Settings,
  externalLink: ExternalLink,
  rotateCcw: RotateCcw,
  save: Save,
  checkCircle: CheckCircle,
  alertCircle: AlertCircle,
};

interface DynamicIconProps extends LucideProps {
  name: string;
}

export function DynamicIcon({ name, ...props }: DynamicIconProps) {
  const Icon = iconMap[name];
  if (!Icon) return null;
  return <Icon {...props} />;
}

export {
  Droplets,
  Wrench,
  Flame,
  Bath,
  Thermometer,
  Search,
  Clock,
  Shield,
  Banknote,
  Award,
  ThumbsUp,
  Headphones,
  Phone,
  Mail,
  MapPin,
  ChevronDown,
  ChevronUp,
  Menu,
  X,
  Star,
  ArrowRight,
  Settings,
  ExternalLink,
  RotateCcw,
  Save,
  CheckCircle,
  AlertCircle,
};
